/**
 * Roundtable AI Module Entry Point
 * ================================
 * Orchestrates the AI pipeline:
 * Audio Chunk → Speech-to-Text (STT) → Speaker Attribution → Standardized Transcript Result
 *
 * 1. TRANSCRIPT DATA CONTRACT:
 * ----------------------------
 * Every transcript generated by this pipeline adheres to the following shape:
 * {
 *   transcriptId: string, // Unique ID for this transcript entry (UUID string)
 *   roomId: string,       // Conversation room identifier
 *   speakerId: string,    // Unique identifier of the speaker (matches participantId from device)
 *   speakerName: string,  // Readable display name of the speaker (e.g. "Mitali")
 *   text: string,         // Transcribed speech text
 *   timestamp: string,    // ISO-8601 formatted timestamp (e.g. "2026-10-04T00:15:00.000Z")
 *   isFinal: boolean,     // Whether this chunk is final (true) or interim/partial preview (false)
 *   confidence: number    // Float between 0.0 and 1.0 representing STT confidence
 * }
 *
 * 2. AUDIO INPUT CONTRACT:
 * ------------------------
 * Expected input for `processAudioChunk(audioChunk)`:
 * {
 *   roomId: string,                      // Required: Room identifier
 *   participantId: string,               // Required: Participant/device identifier
 *   participantName: string,             // Optional: Display name
 *   audioData: Buffer|Uint8Array|string, // Required: Raw audio buffer or base64 chunk
 *   mimeType: string,                    // Optional: 'audio/webm', 'audio/wav', etc.
 *   sampleRate: number,                  // Optional: e.g. 16000
 *   timestamp: number|string,            // Optional: Capture timestamp
 *   isFinal: boolean,                    // Optional: Whether this closes an utterance
 *   mockText: string                     // Optional: Simulated text for testing
 * }
 *
 * 3. SPEAKER ATTRIBUTION:
 * -----------------------
 * Device/participant-based attribution is used because each participant connects via
 * their own device stream. Mapping participantId -> speakerId delivers 0ms latency,
 * 100% deterministic accuracy, and zero ML inference overhead for the hackathon MVP.
 *
 * 4. PLUGGING IN A REAL STT PROVIDER:
 * -----------------------------------
 * When the STT provider is decided (e.g. Deepgram, Whisper, Google Cloud Speech):
 * Create a provider extending `BaseSpeechToTextProvider`, implement `transcribeChunk()`,
 * and call `sttService.setProvider(new RealProvider())`. No other pipeline changes needed.
 */

const crypto = require('crypto');
const {
  validateAudioChunk,
  BaseSpeechToTextProvider,
  MockSpeechToTextProvider,
  SpeechToTextService
} = require('./stt/speechToText');

const {
  attributeSpeaker,
  SpeakerAttributionService
} = require('./speaker/speakerAttribution');

/**
 * Creates and formats a standardized transcript object.
 *
 * @param {Object} params
 * @param {string} [params.transcriptId] - Optional explicit UUID (generated automatically if omitted)
 * @param {string} params.roomId - Required room identifier
 * @param {string} params.speakerId - Required speaker identifier
 * @param {string} [params.speakerName] - Display name for speaker
 * @param {string} params.text - Transcribed text
 * @param {string|number} [params.timestamp] - Timestamp (defaults to current ISO string)
 * @param {boolean} [params.isFinal=true] - Whether transcript segment is final
 * @param {number} [params.confidence=1.0] - Confidence score (0.0 to 1.0)
 * @returns {Object} Conforming to Transcript Data Contract
 */
function createTranscriptResult({
  transcriptId,
  roomId,
  speakerId,
  speakerName = 'Speaker',
  text,
  timestamp,
  isFinal = true,
  confidence = 1.0
}) {
  if (!roomId || typeof roomId !== 'string' || !roomId.trim()) {
    throw new Error('createTranscriptResult error: Missing or invalid "roomId"');
  }
  if (!speakerId || typeof speakerId !== 'string' || !speakerId.trim()) {
    throw new Error('createTranscriptResult error: Missing or invalid "speakerId"');
  }
  if (text === undefined || text === null) {
    throw new Error('createTranscriptResult error: Missing "text" field');
  }

  // Format ISO timestamp
  let formattedTimestamp;
  if (!timestamp) {
    formattedTimestamp = new Date().toISOString();
  } else if (typeof timestamp === 'number') {
    formattedTimestamp = new Date(timestamp).toISOString();
  } else if (typeof timestamp === 'string') {
    formattedTimestamp = new Date(timestamp).toISOString();
  } else {
    formattedTimestamp = new Date().toISOString();
  }

  return {
    transcriptId: transcriptId || crypto.randomUUID(),
    roomId: roomId.trim(),
    speakerId: speakerId.trim(),
    speakerName: typeof speakerName === 'string' && speakerName.trim() ? speakerName.trim() : 'Speaker',
    text: String(text),
    timestamp: formattedTimestamp,
    isFinal: Boolean(isFinal),
    confidence: typeof confidence === 'number' ? Math.max(0, Math.min(1, confidence)) : 1.0
  };
}

// Default singleton instances for zero-configuration use by backend
const defaultSTTService = new SpeechToTextService(new MockSpeechToTextProvider());
const defaultSpeakerService = new SpeakerAttributionService();

/**
 * Main AI pipeline entry point for the backend.
 *
 * Pipeline flow:
 * 1. Validate incoming audio chunk
 * 2. Transcribe via STT service
 * 3. Attribute speaker identity via Speaker Attribution service
 * 4. Package and return standardized transcript result
 *
 * @param {Object} audioChunk - Object meeting Audio Input Contract
 * @param {Object} [options]
 * @param {SpeechToTextService} [options.sttService] - Optional custom STT service instance
 * @param {SpeakerAttributionService} [options.speakerService] - Optional custom speaker service instance
 * @returns {Promise<Object>} Object conforming to Transcript Data Contract
 */
async function processAudioChunk(audioChunk, options = {}) {
  // 1. Basic validation
  validateAudioChunk(audioChunk);

  const activeSTT = options.sttService || defaultSTTService;
  const activeSpeaker = options.speakerService || defaultSpeakerService;

  // 2. Perform STT (returns { text, isFinal, confidence })
  const sttResult = await activeSTT.transcribe(audioChunk);

  // 3. Perform Speaker Attribution (returns { speakerId, speakerName })
  const attribution = activeSpeaker.attribute({
    roomId: audioChunk.roomId,
    participantId: audioChunk.participantId,
    participantName: audioChunk.participantName
  });

  // 4. Return standardized transcript result
  return createTranscriptResult({
    roomId: audioChunk.roomId,
    speakerId: attribution.speakerId,
    speakerName: attribution.speakerName,
    text: sttResult.text,
    timestamp: audioChunk.timestamp,
    isFinal: sttResult.isFinal,
    confidence: sttResult.confidence
  });
}

module.exports = {
  // Main pipeline function
  processAudioChunk,

  // Transcript schema helper
  createTranscriptResult,

  // Services and Providers
  SpeechToTextService,
  BaseSpeechToTextProvider,
  MockSpeechToTextProvider,
  SpeakerAttributionService,
  attributeSpeaker,

  // Default instances
  sttService: defaultSTTService,
  speakerService: defaultSpeakerService
};
